# Generated by Django 3.0.3 on 2020-08-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dpartment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
