# Generated by Django 3.0.3 on 2020-08-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.TextField(choices=[(1, 'Wating'), (2, 'Under Process'), (3, 'Done'), (4, 'Total')], default=1),
        ),
    ]
