# Generated by Django 3.0.3 on 2020-08-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200829_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.TextField(),
        ),
    ]
