# Generated by Django 3.0.3 on 2020-09-02 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('task', '0007_auto_20200901_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='panel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='dashboard.panel'),
        ),
    ]
