# Generated by Django 3.0.3 on 2020-09-02 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200902_0508'),
        ('task', '0008_ticket_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel', to='dashboard.panel'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
