# Generated by Django 3.0.3 on 2020-09-02 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200902_0508'),
        ('task', '0010_remove_ticket_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='panel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='panel', to='dashboard.panel'),
        ),
    ]
