# Generated by Django 3.0.3 on 2020-09-02 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_ticket_panel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='panel',
        ),
    ]
