# Generated by Django 3.0.3 on 2020-09-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_auto_20200902_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='panel',
        ),
    ]
