# Generated by Django 3.0.3 on 2020-09-02 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_auto_20200902_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='panelMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_member', to='dashboard.panel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_panel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('panel', 'user')},
            },
        ),
    ]
